In [1]:
#레몬 포도 분류기
import numpy as np

In [3]:
#입력층
input_data = np.array([[2,3],[5,1]])#2행 2열
print(input_data)
x = input_data.reshape(-1) #벡터화
print(x)

[[2 3]
 [5 1]]
[2 3 5 1]


In [5]:
#가중치 및 편향
w1 = np.array([2,1,-3,3]) #레몬 점수 가중치 벡터 
w2 = np.array([1,-3,1,3]) #포도 점수 가중치 벡터 
b1 = 3                    #레몬 점수 편향
b2 = 3                    #포도 점수 편향

In [9]:
#가중합 <- 위에서 구한 가중치 및 편향으로 구하기
W = np.array([w1,w2]) #가중치 행렬 = 가중치 벡터들의 합
print(W) #2행 2열+2행 2열 = 2행 4열
b = np.array([b1,b2]) # 편향 벡터 = 편향 점수의 합
print(b) 
weight_sum = np.dot(W,x)+b #행렬곱 + 편향벡터 = 가중합
print(weight_sum)

[[ 2  1 -3  3]
 [ 1 -3  1  3]]
[3 3]
[-2  4]


In [10]:
#출력층
res = 1/(1+np.exp(-weight_sum)) #시그모이드를 활성화 함수로 사용
print(res)

[0.11920292 0.98201379]
