In [18]:
import numpy as np
#수학적 계산 관련 함수 제공
import pandas as pd
#데이터를 데이터 프레임 형식으로 다루는 라이브러리. 데이터 이용시 필수
import seaborn as sns
#시각화 1 더 화려함
import matplotlib.pyplot as plt
#시각화 2 덜 화려함
from sklearn import datasets
#사이킷런에서 제공하는 다양한 데이터를 이용 가능

In [19]:
#키가 175이고 몸무게가 65이면 키는 cm, 몸무게는 kg으로 단위가 달라 비교가 어렵다
#데이터 스케일링을 통해 피처 데이터가 단위에 영향을 받지 않도록 하자
#평균, 분산, 최댓값, 최솟값 등을 이용해서 데이터 스케일링을 취함

In [32]:
df = pd.DataFrame([
    [42,'male',12,'reading','class2'],
    [35,'unknown',3,'cooking','class1'],
    [1000,'female',7,'cycling','class3'],
    [1000,'unknown',21,'unknown','unknown']
])
df.columns = ['age','gender','month_birth','hobby','target']
df.loc[df['age']>110,['age']]=np.nan
df.loc[df['gender']=='unknown',['gender']]=np.nan
df.loc[df['month_birth']>12,['month_birth']]=np.nan
df.loc[df['hobby']=='unknown',['hobby']]=np.nan
df.loc[df['target']=='unknown',['target']]=np.nan
df
alter_values = {'age' : 0,    
                'gender':'U',        
                'month_birth':0,            
                'hobby':'U',                
                'target':'class4'}
df7=df.fillna(value=alter_values) 
from sklearn.preprocessing import LabelEncoder #라벨링 함수
df8 = df7
class_label = LabelEncoder()#라벨링 모형 설정
data_value = df8['target'].values#타깃 변수 값 불러오기
y_new = class_label.fit_transform(data_value)#데이터 값 변환
df8['target']=y_new #덮어쓰기
df8

age  gender  month_birth    hobby  target
0  42.0    male         12.0  reading       1
1  35.0       U          3.0  cooking       0
2   0.0  female          7.0  cycling       2
3   0.0       U          0.0        U       3

In [43]:
여기에선 fit, transform이 나오는데
1. fit : 주어진 데이터를 사용해서 스케일러의 파라미터를 학습함
    즉, 데이터에서 각자가 원하는 정보 (std : 평균, 표준편차)(robust : 중위수, 사분위수)...를 추출해서 스케일링에 사용할 준비를 마침
2. transform : fit 메서드로 학습된 파라미터들을 이용해서 데이터를 스케일링함
    
정리하면, fit으로 스케일링 준비를 하고, transform으로 실제로 스케일링을 진행하게 된다.

SyntaxError: invalid syntax (3163024558.py, line 1)

In [ ]:
# 표준화 스케일링
##데이터가 평균 0, 표준 편차가 1이 되도록 변경하는 방법
###(기존 데이터 - 평균) / 표준편차
from sklearn.preprocessing import StandardScaler

std = StandardScaler() 
std.fit(df8[['month_birth']]) #표준화 스케일러에 month_birth열을 적합
x_std = std.transform(df8[['month_birth']]) #적합된 스케일러를 기준으로 month_birth를 변형

In [34]:
#std.fit(df8[['month_birth']])
#x_std = std.transform(df8[['month_birth']])
#는 다음 코드와 똑같음
x_std2=std.fit_transform(df8[['month_birth']])
x_std2

array([[ 1.44444444],
       [-0.55555556],
       [ 0.33333333],
       [-1.22222222]])

In [37]:
np.mean(x_std) #컴퓨터에서 부동 소수점 연산의 한계 때문에 발생하는 것이기 때문에, 정확한 0을 얻기는 어려울 수 있습니다.라는데 흠..

-5.551115123125783e-17

In [38]:
np.std(x_std)

1.0

In [40]:
#로버스트 스케일링
##표준화 스케일을 변형한 방법
###중앙값 사분위수를 사용. 극단값의 영향을 거의 받지 않음
#### (값 - 중위수) / (3사분위수 - 1사부위수)
from sklearn.preprocessing import RobustScaler
robust = RobustScaler()
robust.fit(df8[['month_birth']]) #스케일링대상인 데이터 프레임의 열을 적합
x_robust = robust.transform (df8[['month_birth']]) #적합된 스케일러를 기반으로 값 변환, 결과 확인
x_robust

array([[ 1.16666667],
       [-0.33333333],
       [ 0.33333333],
       [-0.83333333]])

In [41]:
#최소-최대 스케일링
##데이터값의 최댓값이 1, 최솟값 0으로 데이터 값이 가질 수 있는 범위를 제한함
###x-min(x)/max(x)-min(x)
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
minmax.fit(df8[['month_birth']]) #적합
x_minmax=minmax.transform(df8[['month_birth']]) #적합된 스케일러로 데이터 변경
x_minmax

array([[1.        ],
       [0.25      ],
       [0.58333333],
       [0.        ]])

In [42]:
#노멀 스케일링(normalization)
##벡터의 유클리디안 길이(벡터 크기)가 1이 되도록 데이터 값을 변경
###벡터 크기는 관심 x, 방향만 고려할 때 사용
####앞선 스케일러들과 달리 row 기준
from sklearn.preprocessing import Normalizer
normal = Normalizer()
normal.fit(df8[['age','month_birth']]) #피처들을 정하고 적합.
x_normal = normal.transform(df8[['age','month_birth']]) #변경
x_normal

array([[0.96152395, 0.27472113],
       [0.99634665, 0.08540114],
       [0.        , 1.        ],
       [0.        , 0.        ]])

In [ ]:
#표준화 스케일링
from sklearn.preprocessing import StandardScaler #표준화 스케일러라고 가정

stand_scale = StandardScaler() 
x_train_std = stand_scale.fit_transform(x_train) #적합된 스케일러로 x_train 데이터 변경
x_test_std = stand_scale.transform(x_test) #fit <- 적합시키겠다인데, test는 train에 적합되어있는 스케일러를 사용하기 때문에 변경만 한다.