In [1]:
from sklearn import datasets
raw_wine = datasets.load_wine()

In [2]:
X = raw_wine.data
y = raw_wine.target

In [3]:
from sklearn.model_selection import train_test_split
X_tn,X_te,y_tn,y_te = train_test_split(X,y,random_state=0)

In [4]:
from sklearn.preprocessing import StandardScaler
std_scale=StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

In [5]:
#그리드 서치
from sklearn import svm #svm의 분류인 svc도 쓸꺼임
from sklearn.model_selection import StratifiedKFold ##크로스 밸리데이션용 k-flod
from sklearn.model_selection import GridSearchCV # 그리드 서치

param_grid = {'kernel':('linear','rbf'),'C':[0.5,1,10,100]}
#bf' (Radial Basis Function, 방사 기저 함수 커널): 이는 비선형 문제를 해결하기 위한 커널 함수로 가장 널리 사용됩니다. 데이터를 무한한 고차원 공간으로 매핑하여 복잡한 결정 경계를 생성합니다. 'rbf' 커널은 기본값으로 많이 사용되며, 데이터가 비선형적으로 구분되어 있을 때 유용합니다.
kfold = StratifiedKFold(n_splits=5,shuffle=True,random_state=0) #트레이닝 데이터를 5개의 split, shuffle로 데이터를 섞음
svc = svm.SVC(random_state=0) #학습시킬 기본 모형 설정
grid_cv = GridSearchCV(svc,param_grid,cv=kfold,scoring='accuracy') # 그리드 서치 수행. (모형,파라미터, 크로스 밸리데이션 방법, 모형 평가 방법)
grid_cv.fit(X_tn_std,y_tn) #모델에 적합

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=0, shuffle=True),
             estimator=SVC(random_state=0),
             param_grid={'C': [0.5, 1, 10, 100], 'kernel': ('linear', 'rbf')},
             scoring='accuracy')

In [6]:
grid_cv.cv_results_ #그리드 서치 결과 확인

{'mean_fit_time': array([0.00041628, 0.00047622, 0.00037737, 0.00045843, 0.0003685 ,
        0.00044785, 0.00036526, 0.00044231]),
 'std_fit_time': array([5.64161033e-05, 7.08965618e-06, 8.67712619e-06, 1.66048913e-05,
        8.49466360e-06, 1.09720220e-05, 7.58605808e-06, 8.17800054e-06]),
 'mean_score_time': array([0.0001895 , 0.00022039, 0.00016961, 0.00021214, 0.00016918,
        0.00020399, 0.00016656, 0.0002027 ]),
 'std_score_time': array([2.22000346e-05, 3.75946109e-06, 3.06291329e-06, 5.72482677e-06,
        2.13567693e-06, 1.13443158e-06, 1.20253756e-06, 1.34363201e-06]),
 'param_C': masked_array(data=[0.5, 0.5, 1, 1, 10, 10, 100, 100],
              mask=[False, False, False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['linear', 'rbf', 'linear', 'rbf', 'linear', 'rbf',
                    'linear', 'rbf'],
              mask=[False, False, False, False, False, False, False, False],
        fill_

In [7]:
import numpy as np
import pandas as pd
np.transpose(pd.DataFrame(grid_cv.cv_results_)) #상단의 결과를 데이터 프레임 형태로 확인

0  \
mean_fit_time                            0.000416   
std_fit_time                             0.000056   
mean_score_time                          0.000189   
std_score_time                           0.000022   
param_C                                       0.5   
param_kernel                               linear   
params             {'C': 0.5, 'kernel': 'linear'}   
split0_test_score                        0.888889   
split1_test_score                        0.962963   
split2_test_score                        0.925926   
split3_test_score                             1.0   
split4_test_score                        0.846154   
mean_test_score                          0.924786   
std_test_score                           0.054014   
rank_test_score                                 5   

                                             1                             2  \
mean_fit_time                         0.000476                      0.000377   
std_fit_time                          0.000007                      0.000009   
mean_score_time                        0.00022                       0.00017   
std_score_time                        0.000004                      0.000003   
param_C                                    0.5                             1   
param_kernel                               rbf                        linear   
params             {'C': 0.5, 'kernel': 'rbf'}  {'C': 1, 'kernel': 'linear'}   
split0_test_score                     0.962963                      0.888889   
split1_test_score                          1.0                      0.962963   
split2_test_score                     0.962963                      0.925926   
split3_test_score                     0.961538                           1.0   
split4_test_score                          1.0                      0.846154   
mean_test_score                       0.977493                      0.924786   
std_test_score                        0.018384                      0.054014   
rank_test_score                              1                             5   

                                           3                              4  \
mean_fit_time                       0.000458                       0.000368   
std_fit_time                        0.000017                       0.000008   
mean_score_time                     0.000212                       0.000169   
std_score_time                      0.000006                       0.000002   
param_C                                    1                             10   
param_kernel                             rbf                         linear   
params             {'C': 1, 'kernel': 'rbf'}  {'C': 10, 'kernel': 'linear'}   
split0_test_score                   0.925926                       0.888889   
split1_test_score                   0.962963                       0.962963   
split2_test_score                   0.962963                       0.925926   
split3_test_score                   0.961538                            1.0   
split4_test_score                        1.0                       0.846154   
mean_test_score                     0.962678                       0.924786   
std_test_score                      0.023431                       0.054014   
rank_test_score                            2                              5   

                                            5                               6  \
mean_fit_time                        0.000448                        0.000365   
std_fit_time                         0.000011                        0.000008   
mean_score_time                      0.000204                        0.000167   
std_score_time                       0.000001                        0.000001   
param_C                                    10                             100   
param_kernel                              rbf                          linear   
params             {'C': 10, 'kernel': 'rbf'}  {'C': 100, 'kernel': 'linear'}   
split

In [8]:
#가장 좋은 성능 점수를 반환
print(grid_cv.best_score_)
#가장 성능이 뛰어한 파라미터와 커널 
print(grid_cv.best_params_)

0.9774928774928775
{'C': 0.5, 'kernel': 'rbf'}


In [9]:
#최종 모형
#그리드 서치를 통해 구현한 베스트 모형을 최종 모형으로 설정함.
clf = grid_cv.best_estimator_
print(clf)

SVC(C=0.5, random_state=0)


In [10]:
#크로스 밸리데이션 스코어 확인 1
from sklearn.model_selection import cross_validate
metrics = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']
cv_scores = cross_validate(clf,X_tn_std,y_tn,cv=kfold, scoring=metrics)
cv_scores


{'fit_time': array([0.0007937 , 0.00055814, 0.00054407, 0.00059199, 0.00067592]),
 'score_time': array([0.00189114, 0.00165081, 0.00173903, 0.00240493, 0.00193501]),
 'test_accuracy': array([0.96296296, 1.        , 0.96296296, 0.96153846, 1.        ]),
 'test_precision_macro': array([0.96296296, 1.        , 0.96969697, 0.96969697, 1.        ]),
 'test_recall_macro': array([0.96666667, 1.        , 0.96296296, 0.95833333, 1.        ]),
 'test_f1_macro': array([0.9628483 , 1.        , 0.96451914, 0.96190476, 1.        ])}

In [11]:
#크로스 밸리데이션 스코어 확인 2
from sklearn.model_selection import cross_val_score
cv_score = cross_val_score(clf,X_tn_std,y_tn,cv=kfold,scoring='accuracy')
print(cv_score)
print(cv_score.mean())
print(cv_score.std())

[0.96296296 1.         0.96296296 0.96153846 1.        ]
0.9774928774928775
0.01838434849561446


In [12]:
#예측
pred_svm = clf.predict(X_te_std)
print(pred_svm)

[0 2 1 0 1 1 0 2 1 1 2 2 0 1 2 1 0 0 1 0 1 0 0 1 1 1 1 1 1 2 0 0 1 0 0 0 2
 1 1 2 0 0 1 1 1]


In [13]:
#정확도
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_te,pred_svm)
print(accuracy)

1.0


In [14]:
#confusion matrix
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te,pred_svm)
print(conf_matrix)

[[16  0  0]
 [ 0 21  0]
 [ 0  0  8]]


In [15]:
#분류 리포트
from sklearn.metrics import classification_report
class_report = classification_report(y_te,pred_svm)
print(class_report)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      1.00      1.00        21
           2       1.00      1.00      1.00         8

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

